#!/bin/sh -e

# Take a screenshot
scrot /tmp/screen_locked.png

# Pixellate it 10x
#mogrify -scale 10% -scale 1000% /tmp/screen_locked.png

# Lock screen displaying this image.
i3lock -i /tmp/screen_locked.png -n

# Turn the screen off after a delay.
sleep 60; pgrep i3lock && xset dpms force off

exec xautolock -detectsleep -b
  -time 1 -locker "i3lock -i /home/steve/Pictures/wallpapers/archwallpaper.png -t -n" \
 -notify 30 \
  -notifier "notify-send -u critical -t 10000 -- 'LOCKING screen in 30 seconds'"

